### ISSUE TITLE
Don't find necessary plugins

### ISSUE THREAD

**Issue by Fantazzj** [chadparry/kodi-plugin.program.remote.control.browser#6] opened 2020-04-09 18:35 UTC
Hi,
When I open the settings it says there are three missing plugins (psutil, pylirc2 and pyalsaaudio), even if I try installing them it stills give me the warnings. It also says "insufficent memory".
Trying opening a website it doesn't start or it gives me error in the browser.
I'm using a RaspberryPi 3 model B with DietPi, Kodi 18.6, I've got LXDE installed and I'm trying opening chromium
Thanks for the help

**Comment by chadparry** [comment] 2020-05-09 02:59
Looks like this is due to known regressions in Kodi Leia: https://forum.kodi.tv/showthread.php?tid=321370 . I'll see if I can find a workaround.

**Comment by chadparry** [comment] 2020-05-09 05:53
There are many bugs in the addon settings in Kodi 18 (Leia). The documentation says they won't be fixed until Kodi 19 (Matrix). See https://kodi.wiki/view/Add-on_settings_conversion#Preface . None of the docs hint at a workaround, and I couldn't find one myself. So in the meantime, we'll have to live with those spurious warnings.

For your other issue, where the browser couldn't start, that could be because of changes in Kodi 18 that had broken my addon. You need to be on at least version 1.5.0 of the addon to be compatible with Kodi 18.6. Please verify you have updated recently. The most recent versions have not been published to the Kodi addon repository yet, so you'll have to fetch them from my personal repository, (https://chad.parry.org/software/kodi/repository.chad.parry.org/repository.chad.parry.org-3.1.0.zip).

**Closed as completed** 2021-03-23 09:22 UTC
